### ISSUE TITLE
Progress bar to show user the stream is running.

### ISSUE THREAD

**Issue by jcode89** [jcode89/DataDotPy#23]
Upon learning about this new module [tqdm](https://pypi.python.org/pypi/tqdm). I feel it would be nifty to be able to show the user the progress of the stream. It isn't crucial to the overall program, but a nice little feature that would make it friendlier to use.

**Comment by jamalhansen** [comment]
up vote +1

**Comment by jcode89** [comment]
Awesome! I will look at our code and see how/if this can be done.
