### ISSUE TITLE
Make a centralized config class

### ISSUE THREAD

**Issue by jamalhansen** [jcode89/DataDotPy#5]
Make a generic configuration class that contains configuration data like twitter API keys

This can later be leveraged to create a service to populate the twitter API info from environment variables or other sources.

**Comment by jcode89** [comment]
Absolutely helpful. Before the Flask app, my original idea with this program was an easy to use CLI tool. Something you could use to scour twitter without having to go through the hassle of writing a program yourself.

**Comment by jamalhansen** [comment]
Cool, I think that we can, with time and effort do both

**Comment by jcode89** [comment]
😃 That's what I like to hear.
